/** @type {import('./index.js').SkillEntry[]} */
export default [
  { canonical: 'Node.js',        category: 'Backend', weight: 0.97, aliases: ['NodeJS', 'Node JS', 'Node', 'nodejs'] },
  { canonical: 'Express.js',     category: 'Backend', weight: 0.93, aliases: ['Express', 'ExpressJS', 'Express JS', 'expressjs'] },
  { canonical: 'Fastify',        category: 'Backend', weight: 0.85, aliases: ['Fastify.js'] },
  { canonical: 'Hapi.js',        category: 'Backend', weight: 0.80, aliases: ['Hapi', 'HapiJS'] },
  { canonical: 'Koa.js',         category: 'Backend', weight: 0.80, aliases: ['Koa', 'KoaJS'] },
  { canonical: 'Python',         category: 'Backend', weight: 0.97, aliases: ['Python 3', 'Python3', 'py'] },
  { canonical: 'Django',         category: 'Backend', weight: 0.92, aliases: ['Django REST', 'Django Framework', 'DRF'] },
  { canonical: 'Flask',          category: 'Backend', weight: 0.90, aliases: ['Flask API', 'Flask Python'] },
  { canonical: 'FastAPI',        category: 'Backend', weight: 0.90, aliases: ['Fast API', 'fastapi'] },
  { canonical: 'Java',           category: 'Backend', weight: 0.95, aliases: ['Java SE', 'Java EE', 'Java 8', 'Java 11', 'Java 17'] },
  { canonical: 'Spring Boot',    category: 'Backend', weight: 0.92, aliases: ['Spring', 'SpringBoot', 'Spring Framework', 'Spring MVC'] },
  { canonical: 'Hibernate',      category: 'Backend', weight: 0.83, aliases: ['JPA', 'Java Persistence API'] },
  { canonical: 'PHP',            category: 'Backend', weight: 0.90, aliases: ['PHP 7', 'PHP 8', 'PHP7', 'PHP8'] },
  { canonical: 'Laravel',        category: 'Backend', weight: 0.92, aliases: ['Laravel PHP', 'Laravel Framework'] },
  { canonical: 'Symfony',        category: 'Backend', weight: 0.82, aliases: ['Symfony Framework', 'Symfony PHP'] },
  { canonical: 'CodeIgniter',    category: 'Backend', weight: 0.80, aliases: ['CI Framework', 'CodeIgniter PHP'] },
  { canonical: 'Ruby',           category: 'Backend', weight: 0.85, aliases: ['Ruby on Rails', 'RoR'] },
  { canonical: 'Rails',          category: 'Backend', weight: 0.88, aliases: ['Ruby on Rails', 'RoR', 'Rails Framework'] },
  { canonical: 'Go',             category: 'Backend', weight: 0.88, aliases: ['Golang', 'Go Lang', 'Go Programming'] },
  { canonical: 'Rust',           category: 'Backend', weight: 0.85, aliases: ['Rust Lang', 'Rust Programming'] },
  { canonical: 'C#',             category: 'Backend', weight: 0.90, aliases: ['C Sharp', 'CSharp', 'C# .NET', 'dotnet C#'] },
  { canonical: '.NET',           category: 'Backend', weight: 0.90, aliases: ['ASP.NET', 'ASP.NET Core', '.NET Core', 'DotNet', '.NET Framework', 'dotnet'] },
  { canonical: 'C++',            category: 'Backend', weight: 0.88, aliases: ['CPP', 'C Plus Plus', 'C/C++'] },
  { canonical: 'C',              category: 'Backend', weight: 0.83, aliases: ['C Programming', 'C Language'] },
  { canonical: 'Kotlin',         category: 'Backend', weight: 0.87, aliases: ['Kotlin JVM', 'Kotlin Language'] },
  { canonical: 'Scala',          category: 'Backend', weight: 0.83, aliases: ['Scala Language', 'Scala JVM'] },
  { canonical: 'Elixir',         category: 'Backend', weight: 0.78, aliases: ['Elixir Language', 'Phoenix Framework'] },
  { canonical: 'GraphQL',        category: 'Backend', weight: 0.88, aliases: ['Graph QL', 'GraphQL API', 'gql'] },
  { canonical: 'gRPC',           category: 'Backend', weight: 0.83, aliases: ['Protocol Buffers', 'protobuf'] },
  { canonical: 'REST API',       category: 'Backend', weight: 0.88, aliases: ['RESTful API', 'REST APIs', 'RESTful Services', 'REST Services', 'RESTful Web Services'] },
  { canonical: 'WebSocket',      category: 'Backend', weight: 0.83, aliases: ['Web Sockets', 'WebSockets', 'Socket.io'] },
  { canonical: 'Message Queue',  category: 'Backend', weight: 0.82, aliases: ['MQ', 'RabbitMQ', 'Message Broker'] },
  { canonical: 'Apache Kafka',   category: 'Backend', weight: 0.88, aliases: ['Kafka', 'Kafka Streams'] },
  { canonical: 'Microservices',  category: 'Backend', weight: 0.88, aliases: ['Micro Services', 'Microservice Architecture'] },
  { canonical: 'Serverless',     category: 'Backend', weight: 0.85, aliases: ['Serverless Architecture', 'FaaS', 'Function as a Service'] },
]
