/** @type {import('./index.js').SkillEntry[]} */
export default [
  { canonical: 'Bookkeeping',        category: 'Finance', weight: 0.88, aliases: ['Book Keeping', 'Bookkeeper'] },
  { canonical: 'Financial Reporting', category: 'Finance', weight: 0.87, aliases: ['Financial Reports', 'Financial Statements', 'FS Preparation'] },
  { canonical: 'Tax Preparation',    category: 'Finance', weight: 0.85, aliases: ['Tax Filing', 'Taxation', 'Tax Compliance', 'Income Tax Return', 'ITR'] },
  { canonical: 'Auditing',           category: 'Finance', weight: 0.87, aliases: ['Internal Audit', 'External Audit', 'Financial Audit'] },
  { canonical: 'Payroll',            category: 'Finance', weight: 0.87, aliases: ['Payroll Processing', 'Payroll Management', 'Payroll Administration'] },
  { canonical: 'QuickBooks',         category: 'Finance', weight: 0.88, aliases: ['Quick Books', 'QuickBooks Online', 'QuickBooks Desktop'] },
  { canonical: 'SAP',                category: 'Finance', weight: 0.90, aliases: ['SAP ERP', 'SAP S/4HANA', 'SAP FICO'] },
  { canonical: 'Xero',               category: 'Finance', weight: 0.83, aliases: ['Xero Accounting', 'Xero Software'] },
  { canonical: 'Oracle Financials',  category: 'Finance', weight: 0.83, aliases: ['Oracle ERP', 'Oracle Finance'] },
  { canonical: 'Accounts Payable',   category: 'Finance', weight: 0.85, aliases: ['AP', 'AP Processing', 'Payables'] },
  { canonical: 'Accounts Receivable', category: 'Finance', weight: 0.85, aliases: ['AR', 'AR Management', 'Receivables'] },
  { canonical: 'General Ledger',     category: 'Finance', weight: 0.83, aliases: ['GL', 'GL Accounting', 'General Accounting'] },
  { canonical: 'Bank Reconciliation', category: 'Finance', weight: 0.83, aliases: ['Bank Recon', 'Bank Reconciling'] },
  { canonical: 'Financial Analysis', category: 'Finance', weight: 0.87, aliases: ['Financial Modeling', 'Financial Planning', 'FP&A'] },
  { canonical: 'Budgeting',          category: 'Finance', weight: 0.85, aliases: ['Budget Preparation', 'Budget Management', 'Budget Planning'] },
  { canonical: 'GAAP',               category: 'Finance', weight: 0.83, aliases: ['Generally Accepted Accounting Principles'] },
  { canonical: 'IFRS',               category: 'Finance', weight: 0.83, aliases: ['International Financial Reporting Standards'] },
  { canonical: 'Cost Accounting',    category: 'Finance', weight: 0.83, aliases: ['Cost Analysis', 'Cost Management', 'Costing'] },
  { canonical: 'BIR Compliance',     category: 'Finance', weight: 0.80, aliases: ['BIR Filing', 'Bureau of Internal Revenue'] },
  { canonical: 'Investment Analysis', category: 'Finance', weight: 0.80, aliases: ['Investment Management', 'Portfolio Analysis'] },
  { canonical: 'Credit Analysis',    category: 'Finance', weight: 0.80, aliases: ['Credit Risk', 'Credit Evaluation'] },
  { canonical: 'Forecasting',        category: 'Finance', weight: 0.83, aliases: ['Financial Forecasting', 'Revenue Forecasting'] },
]
