/** @type {import('./index.js').SkillEntry[]} */
export default [
  { canonical: 'AWS',                  category: 'Cloud', weight: 0.95, aliases: ['Amazon Web Services', 'Amazon AWS', 'AWS Cloud'] },
  { canonical: 'AWS Lambda',           category: 'Cloud', weight: 0.88, aliases: ['Lambda', 'AWS Serverless'] },
  { canonical: 'AWS EC2',              category: 'Cloud', weight: 0.87, aliases: ['EC2', 'Amazon EC2', 'Elastic Compute Cloud'] },
  { canonical: 'AWS S3',               category: 'Cloud', weight: 0.87, aliases: ['S3', 'Amazon S3', 'Simple Storage Service'] },
  { canonical: 'AWS RDS',              category: 'Cloud', weight: 0.85, aliases: ['RDS', 'Amazon RDS', 'Relational Database Service'] },
  { canonical: 'AWS ECS',              category: 'Cloud', weight: 0.83, aliases: ['ECS', 'Amazon ECS', 'Elastic Container Service'] },
  { canonical: 'AWS EKS',              category: 'Cloud', weight: 0.83, aliases: ['EKS', 'Amazon EKS', 'Elastic Kubernetes Service'] },
  { canonical: 'AWS CloudFormation',   category: 'Cloud', weight: 0.82, aliases: ['CloudFormation', 'CFN'] },
  { canonical: 'AWS CloudFront',       category: 'Cloud', weight: 0.82, aliases: ['CloudFront', 'CDN AWS'] },
  { canonical: 'AWS SQS',              category: 'Cloud', weight: 0.82, aliases: ['SQS', 'Amazon SQS', 'Simple Queue Service'] },
  { canonical: 'AWS SNS',              category: 'Cloud', weight: 0.80, aliases: ['SNS', 'Amazon SNS'] },
  { canonical: 'AWS IAM',              category: 'Cloud', weight: 0.82, aliases: ['IAM', 'Identity and Access Management'] },
  { canonical: 'AWS API Gateway',      category: 'Cloud', weight: 0.83, aliases: ['API Gateway', 'Amazon API Gateway'] },
  { canonical: 'Azure',                category: 'Cloud', weight: 0.93, aliases: ['Microsoft Azure', 'MS Azure', 'Azure Cloud'] },
  { canonical: 'Azure Functions',      category: 'Cloud', weight: 0.85, aliases: ['Azure Serverless', 'Azure Function Apps'] },
  { canonical: 'Azure DevOps',         category: 'Cloud', weight: 0.87, aliases: ['AzureDevOps', 'VSTS', 'Azure Pipelines'] },
  { canonical: 'Azure Kubernetes',     category: 'Cloud', weight: 0.83, aliases: ['AKS', 'Azure Kubernetes Service'] },
  { canonical: 'Google Cloud',         category: 'Cloud', weight: 0.92, aliases: ['GCP', 'Google Cloud Platform', 'Google Cloud Services'] },
  { canonical: 'Google Cloud Run',     category: 'Cloud', weight: 0.82, aliases: ['Cloud Run', 'GCP Cloud Run'] },
  { canonical: 'Google Kubernetes Engine', category: 'Cloud', weight: 0.82, aliases: ['GKE', 'GCP Kubernetes'] },
  { canonical: 'Heroku',               category: 'Cloud', weight: 0.83, aliases: ['Heroku Platform', 'Heroku PaaS'] },
  { canonical: 'Vercel',               category: 'Cloud', weight: 0.85, aliases: ['Vercel Cloud', 'Vercel Deploy'] },
  { canonical: 'Netlify',              category: 'Cloud', weight: 0.83, aliases: ['Netlify Deploy', 'Netlify Platform'] },
  { canonical: 'DigitalOcean',         category: 'Cloud', weight: 0.83, aliases: ['Digital Ocean', 'DO Cloud'] },
  { canonical: 'Cloudflare',           category: 'Cloud', weight: 0.83, aliases: ['Cloudflare CDN', 'Cloudflare Workers'] },
  { canonical: 'Firebase',             category: 'Cloud', weight: 0.87, aliases: ['Google Firebase', 'Firebase Cloud'] },
  { canonical: 'Supabase',             category: 'Cloud', weight: 0.83, aliases: ['Supabase Cloud'] },
  { canonical: 'Cloud Computing',      category: 'Cloud', weight: 0.85, aliases: ['Cloud Services', 'Cloud Infrastructure'] },
  { canonical: 'Infrastructure as Code', category: 'Cloud', weight: 0.83, aliases: ['IaC', 'Infrastructure as a Code'] },
  { canonical: 'CDN',                  category: 'Cloud', weight: 0.80, aliases: ['Content Delivery Network'] },
]
