/** @type {import('./index.js').SkillEntry[]} */
export default [
  { canonical: 'MySQL',          category: 'Database', weight: 0.95, aliases: ['My SQL', 'MySQL DB', 'MySql', 'Mysql'] },
  { canonical: 'PostgreSQL',     category: 'Database', weight: 0.95, aliases: ['Postgres', 'PostGres', 'PostgresQL', 'Postgre SQL', 'PSQL'] },
  { canonical: 'MongoDB',        category: 'Database', weight: 0.93, aliases: ['Mongo', 'Mongo DB', 'MongoDB Atlas'] },
  { canonical: 'SQLite',         category: 'Database', weight: 0.85, aliases: ['SQLite3', 'SQLite DB'] },
  { canonical: 'Microsoft SQL Server', category: 'Database', weight: 0.88, aliases: ['MSSQL', 'MS SQL', 'SQL Server', 'MS SQL Server', 'T-SQL'] },
  { canonical: 'Oracle Database',category: 'Database', weight: 0.85, aliases: ['Oracle DB', 'Oracle SQL', 'OracleDB', 'Oracle'] },
  { canonical: 'Redis',          category: 'Database', weight: 0.90, aliases: ['Redis Cache', 'RedisDB'] },
  { canonical: 'Elasticsearch',  category: 'Database', weight: 0.87, aliases: ['Elastic Search', 'ES', 'ELK Stack'] },
  { canonical: 'Cassandra',      category: 'Database', weight: 0.83, aliases: ['Apache Cassandra', 'NoSQL Cassandra'] },
  { canonical: 'DynamoDB',       category: 'Database', weight: 0.85, aliases: ['AWS DynamoDB', 'Amazon DynamoDB'] },
  { canonical: 'Firebase',       category: 'Database', weight: 0.88, aliases: ['Firebase Realtime Database', 'Firestore', 'Firebase DB', 'Google Firebase'] },
  { canonical: 'Supabase',       category: 'Database', weight: 0.85, aliases: ['Supabase DB', 'Supabase Postgres'] },
  { canonical: 'MariaDB',        category: 'Database', weight: 0.83, aliases: ['Maria DB', 'MariaDB Server'] },
  { canonical: 'CouchDB',        category: 'Database', weight: 0.75, aliases: ['Apache CouchDB', 'Couch DB'] },
  { canonical: 'Neo4j',          category: 'Database', weight: 0.78, aliases: ['Neo4J', 'Graph Database'] },
  { canonical: 'InfluxDB',       category: 'Database', weight: 0.78, aliases: ['Influx DB', 'Time Series DB'] },
  { canonical: 'Snowflake',      category: 'Database', weight: 0.83, aliases: ['Snowflake DB', 'Snowflake Cloud'] },
  { canonical: 'BigQuery',       category: 'Database', weight: 0.83, aliases: ['Google BigQuery', 'GCP BigQuery'] },
  { canonical: 'SQL',            category: 'Database', weight: 0.92, aliases: ['Structured Query Language', 'SQL Queries', 'Advanced SQL'] },
  { canonical: 'NoSQL',          category: 'Database', weight: 0.85, aliases: ['No SQL', 'Non-relational Database'] },
  { canonical: 'ORM',            category: 'Database', weight: 0.82, aliases: ['Object-Relational Mapping', 'Sequelize', 'Prisma', 'TypeORM'] },
  { canonical: 'Prisma',         category: 'Database', weight: 0.85, aliases: ['Prisma ORM', 'Prisma Client'] },
  { canonical: 'Sequelize',      category: 'Database', weight: 0.83, aliases: ['Sequelize ORM', 'SequelizeJS'] },
]
