/** @type {import('./index.js').SkillEntry[]} */
export default [
  { canonical: 'Docker',          category: 'DevOps', weight: 0.95, aliases: ['Docker Container', 'Docker Compose', 'Dockerfile', 'Containerization'] },
  { canonical: 'Kubernetes',      category: 'DevOps', weight: 0.93, aliases: ['K8s', 'k8s', 'Kube', 'Container Orchestration'] },
  { canonical: 'Terraform',       category: 'DevOps', weight: 0.90, aliases: ['Terraform IaC', 'HashiCorp Terraform'] },
  { canonical: 'Ansible',         category: 'DevOps', weight: 0.87, aliases: ['Ansible Automation', 'Ansible Playbook'] },
  { canonical: 'Jenkins',         category: 'DevOps', weight: 0.88, aliases: ['Jenkins CI', 'Jenkins Pipeline', 'Jenkins CI/CD'] },
  { canonical: 'GitHub Actions',  category: 'DevOps', weight: 0.90, aliases: ['GH Actions', 'Github Actions', 'GitHub CI/CD'] },
  { canonical: 'GitLab CI/CD',    category: 'DevOps', weight: 0.87, aliases: ['GitLab CI', 'GitLab Pipelines'] },
  { canonical: 'CircleCI',        category: 'DevOps', weight: 0.83, aliases: ['Circle CI'] },
  { canonical: 'Travis CI',       category: 'DevOps', weight: 0.80, aliases: ['TravisCI'] },
  { canonical: 'CI/CD',           category: 'DevOps', weight: 0.90, aliases: ['Continuous Integration', 'Continuous Deployment', 'Continuous Delivery', 'CI CD'] },
  { canonical: 'Git',             category: 'DevOps', weight: 0.97, aliases: ['Git SCM', 'Git Version Control'] },
  { canonical: 'GitHub',          category: 'DevOps', weight: 0.95, aliases: ['Git Hub', 'Github'] },
  { canonical: 'GitLab',          category: 'DevOps', weight: 0.88, aliases: ['Git Lab'] },
  { canonical: 'Bitbucket',       category: 'DevOps', weight: 0.83, aliases: ['Bit Bucket', 'Atlassian Bitbucket'] },
  { canonical: 'Linux',           category: 'DevOps', weight: 0.92, aliases: ['Linux OS', 'Linux Server', 'Unix', 'Unix/Linux'] },
  { canonical: 'Ubuntu',          category: 'DevOps', weight: 0.85, aliases: ['Ubuntu Server', 'Ubuntu Linux'] },
  { canonical: 'CentOS',          category: 'DevOps', weight: 0.80, aliases: ['CentOS Linux'] },
  { canonical: 'Bash',            category: 'DevOps', weight: 0.88, aliases: ['Bash Scripting', 'Shell Scripting', 'Shell Script', 'Bash Script'] },
  { canonical: 'Nginx',           category: 'DevOps', weight: 0.87, aliases: ['NGINX', 'Nginx Server', 'Nginx Web Server'] },
  { canonical: 'Apache',          category: 'DevOps', weight: 0.83, aliases: ['Apache HTTP Server', 'Apache Web Server', 'httpd'] },
  { canonical: 'Prometheus',      category: 'DevOps', weight: 0.83, aliases: ['Prometheus Monitoring'] },
  { canonical: 'Grafana',         category: 'DevOps', weight: 0.83, aliases: ['Grafana Dashboard', 'Grafana Monitoring'] },
  { canonical: 'ELK Stack',       category: 'DevOps', weight: 0.83, aliases: ['Elasticsearch Logstash Kibana', 'ELK', 'Elastic Stack'] },
  { canonical: 'Vault',           category: 'DevOps', weight: 0.78, aliases: ['HashiCorp Vault', 'Secrets Management'] },
  { canonical: 'Helm',            category: 'DevOps', weight: 0.80, aliases: ['Helm Charts', 'Kubernetes Helm'] },
  { canonical: 'ArgoCD',          category: 'DevOps', weight: 0.80, aliases: ['Argo CD', 'GitOps'] },
  { canonical: 'SonarQube',       category: 'DevOps', weight: 0.80, aliases: ['Sonar Qube', 'Code Quality'] },
]
