/** @type {import('./index.js').SkillEntry[]} */
export default [
  { canonical: 'HTML',         category: 'Frontend', weight: 0.90, aliases: ['HTML5', 'HyperText Markup Language'] },
  { canonical: 'CSS',          category: 'Frontend', weight: 0.90, aliases: ['CSS3', 'Cascading Style Sheets'] },
  { canonical: 'JavaScript',   category: 'Frontend', weight: 0.98, aliases: ['JS', 'Javascript', 'Java Script', 'ECMAScript', 'ES6', 'ES2015', 'ES2020', 'ES6+'] },
  { canonical: 'TypeScript',   category: 'Frontend', weight: 0.95, aliases: ['TS', 'Typescript'] },
  { canonical: 'React',        category: 'Frontend', weight: 0.97, aliases: ['ReactJS', 'React.js', 'React JS', 'React Framework', 'ReactJs'] },
  { canonical: 'Vue.js',       category: 'Frontend', weight: 0.93, aliases: ['Vue', 'VueJS', 'Vue JS', 'Vue.js', 'Vuejs'] },
  { canonical: 'Angular',      category: 'Frontend', weight: 0.93, aliases: ['AngularJS', 'Angular.js', 'Angular JS', 'Angular 2+'] },
  { canonical: 'Next.js',      category: 'Frontend', weight: 0.92, aliases: ['NextJS', 'Next JS', 'Nextjs'] },
  { canonical: 'Nuxt.js',      category: 'Frontend', weight: 0.88, aliases: ['NuxtJS', 'Nuxt JS', 'Nuxtjs'] },
  { canonical: 'Svelte',       category: 'Frontend', weight: 0.85, aliases: ['SvelteKit', 'Svelte.js'] },
  { canonical: 'Remix',        category: 'Frontend', weight: 0.83, aliases: ['Remix.js', 'RemixJS'] },
  { canonical: 'Gatsby',       category: 'Frontend', weight: 0.83, aliases: ['GatsbyJS', 'Gatsby.js'] },
  { canonical: 'jQuery',       category: 'Frontend', weight: 0.82, aliases: ['JQuery', 'jquery', 'jQuery.js'] },
  { canonical: 'Tailwind CSS', category: 'Frontend', weight: 0.90, aliases: ['Tailwind', 'TailwindCSS', 'Tailwind CSS', 'tailwindcss'] },
  { canonical: 'Bootstrap',    category: 'Frontend', weight: 0.88, aliases: ['Bootstrap CSS', 'Bootstrap 4', 'Bootstrap 5', 'Twitter Bootstrap'] },
  { canonical: 'Material UI',  category: 'Frontend', weight: 0.87, aliases: ['MUI', 'Material-UI', 'MaterialUI', 'Material Design'] },
  { canonical: 'Chakra UI',    category: 'Frontend', weight: 0.83, aliases: ['ChakraUI', 'Chakra'] },
  { canonical: 'Sass',         category: 'Frontend', weight: 0.85, aliases: ['SCSS', 'Sass/SCSS'] },
  { canonical: 'Less',         category: 'Frontend', weight: 0.78, aliases: ['LessCSS', 'Less CSS'] },
  { canonical: 'Webpack',      category: 'Frontend', weight: 0.85, aliases: ['Webpack 5', 'webpack'] },
  { canonical: 'Vite',         category: 'Frontend', weight: 0.87, aliases: ['Vite.js', 'ViteJS'] },
  { canonical: 'Parcel',       category: 'Frontend', weight: 0.75, aliases: ['Parcel.js', 'ParcelJS'] },
  { canonical: 'Babel',        category: 'Frontend', weight: 0.80, aliases: ['Babel.js', 'BabelJS'] },
  { canonical: 'Redux',        category: 'Frontend', weight: 0.88, aliases: ['Redux.js', 'Redux Toolkit', 'RTK'] },
  { canonical: 'Zustand',      category: 'Frontend', weight: 0.82, aliases: [] },
  { canonical: 'Pinia',        category: 'Frontend', weight: 0.80, aliases: [] },
  { canonical: 'GraphQL',      category: 'Frontend', weight: 0.88, aliases: ['Graph QL', 'Graph-QL'] },
  { canonical: 'Apollo',       category: 'Frontend', weight: 0.83, aliases: ['Apollo Client', 'Apollo GraphQL'] },
  { canonical: 'Axios',        category: 'Frontend', weight: 0.83, aliases: ['axios'] },
  { canonical: 'REST API',     category: 'Frontend', weight: 0.88, aliases: ['RESTful API', 'REST APIs', 'RESTful', 'REST', 'Restful API', 'REST Services'] },
  { canonical: 'WebSocket',    category: 'Frontend', weight: 0.83, aliases: ['Web Socket', 'WebSockets'] },
  { canonical: 'PWA',          category: 'Frontend', weight: 0.82, aliases: ['Progressive Web App', 'Progressive Web Application'] },
  { canonical: 'Responsive Design', category: 'Frontend', weight: 0.85, aliases: ['Responsive Web Design', 'RWD', 'Mobile-First Design'] },
  { canonical: 'Web Accessibility', category: 'Frontend', weight: 0.78, aliases: ['WCAG', 'Accessibility', 'a11y', 'ARIA'] },
  { canonical: 'Storybook',    category: 'Frontend', weight: 0.80, aliases: ['StorybookJS', 'Storybook.js'] },
  { canonical: 'Three.js',     category: 'Frontend', weight: 0.80, aliases: ['ThreeJS', 'Three JS', 'WebGL'] },
  { canonical: 'D3.js',        category: 'Frontend', weight: 0.80, aliases: ['D3', 'D3JS', 'Data-Driven Documents'] },
]
