/** @type {import('./index.js').SkillEntry[]} */
export default [
  { canonical: 'Patient Care',         category: 'Healthcare', weight: 0.90, aliases: ['Patient Assessment', 'Patient Management', 'Bedside Care'] },
  { canonical: 'Nursing',              category: 'Healthcare', weight: 0.90, aliases: ['Registered Nursing', 'Clinical Nursing', 'Professional Nursing'] },
  { canonical: 'Clinical Assessment',  category: 'Healthcare', weight: 0.85, aliases: ['Physical Assessment', 'Clinical Evaluation'] },
  { canonical: 'Medication Administration', category: 'Healthcare', weight: 0.85, aliases: ['Drug Administration', 'Medication Management'] },
  { canonical: 'Electronic Health Records', category: 'Healthcare', weight: 0.85, aliases: ['EHR', 'EMR', 'Electronic Medical Records', 'Health Records Management'] },
  { canonical: 'IV Therapy',           category: 'Healthcare', weight: 0.83, aliases: ['Intravenous Therapy', 'IV Insertion', 'IV Line'] },
  { canonical: 'Wound Care',           category: 'Healthcare', weight: 0.83, aliases: ['Wound Management', 'Wound Dressing'] },
  { canonical: 'Phlebotomy',           category: 'Healthcare', weight: 0.82, aliases: ['Blood Extraction', 'Venipuncture'] },
  { canonical: 'CPR',                  category: 'Healthcare', weight: 0.88, aliases: ['Cardiopulmonary Resuscitation', 'Basic Life Support', 'BLS', 'BCLS'] },
  { canonical: 'ACLS',                 category: 'Healthcare', weight: 0.83, aliases: ['Advanced Cardiac Life Support', 'Advanced Life Support'] },
  { canonical: 'Vital Signs',          category: 'Healthcare', weight: 0.85, aliases: ['VS Monitoring', 'Signs Monitoring'] },
  { canonical: 'Triage',               category: 'Healthcare', weight: 0.83, aliases: ['Emergency Triage', 'Patient Triage'] },
  { canonical: 'Emergency Care',       category: 'Healthcare', weight: 0.83, aliases: ['Emergency Room', 'ER Nursing', 'Emergency Medicine'] },
  { canonical: 'Pediatrics',           category: 'Healthcare', weight: 0.82, aliases: ['Pediatric Nursing', 'Pediatric Care'] },
  { canonical: 'ICU',                  category: 'Healthcare', weight: 0.83, aliases: ['Intensive Care Unit', 'Critical Care', 'Critical Care Nursing'] },
  { canonical: 'Medical Coding',       category: 'Healthcare', weight: 0.82, aliases: ['ICD-10', 'CPT Coding', 'Medical Classification'] },
  { canonical: 'HIPAA',                category: 'Healthcare', weight: 0.82, aliases: ['Patient Privacy', 'Health Information Privacy'] },
  { canonical: 'Infection Control',    category: 'Healthcare', weight: 0.82, aliases: ['Infection Prevention', 'Aseptic Technique'] },
  { canonical: 'Pharmacology',         category: 'Healthcare', weight: 0.82, aliases: ['Drug Knowledge', 'Pharmaceutical Knowledge'] },
  { canonical: 'Patient Safety',       category: 'Healthcare', weight: 0.83, aliases: ['Safety Protocols', 'Patient Safety Practices'] },
  { canonical: 'Medical Terminology',  category: 'Healthcare', weight: 0.83, aliases: ['Medical Terms', 'Healthcare Terminology'] },
  { canonical: 'PRC License',          category: 'Healthcare', weight: 0.83, aliases: ['PRC', 'Professional Regulation Commission License', 'Nursing License'] },
]
