/** @type {import('./index.js').SkillEntry[]} */
export default [
  { canonical: 'Visual Studio Code', category: 'Tools', weight: 0.88, aliases: ['VS Code', 'VSCode', 'VSC', 'Visual Studio Code IDE'] },
  { canonical: 'Visual Studio',      category: 'Tools', weight: 0.83, aliases: ['Microsoft Visual Studio', 'VS'] },
  { canonical: 'IntelliJ IDEA',      category: 'Tools', weight: 0.83, aliases: ['IntelliJ', 'JetBrains IntelliJ'] },
  { canonical: 'WebStorm',           category: 'Tools', weight: 0.80, aliases: ['JetBrains WebStorm'] },
  { canonical: 'PyCharm',            category: 'Tools', weight: 0.80, aliases: ['JetBrains PyCharm', 'Python IDE'] },
  { canonical: 'Eclipse',            category: 'Tools', weight: 0.80, aliases: ['Eclipse IDE', 'Eclipse Java'] },
  { canonical: 'Android Studio',     category: 'Tools', weight: 0.83, aliases: ['Android IDE'] },
  { canonical: 'Xcode',              category: 'Tools', weight: 0.83, aliases: ['Apple Xcode', 'iOS IDE'] },
  { canonical: 'Figma',              category: 'Tools', weight: 0.93, aliases: ['Figma Design', 'Figma UI'] },
  { canonical: 'Adobe XD',           category: 'Tools', weight: 0.88, aliases: ['XD', 'AdobeXD'] },
  { canonical: 'Sketch',             category: 'Tools', weight: 0.83, aliases: ['Sketch App', 'Sketch Design'] },
  { canonical: 'Adobe Photoshop',    category: 'Tools', weight: 0.88, aliases: ['Photoshop', 'PS', 'Adobe PS'] },
  { canonical: 'Adobe Illustrator',  category: 'Tools', weight: 0.85, aliases: ['Illustrator', 'AI', 'Adobe AI'] },
  { canonical: 'Adobe Premiere Pro', category: 'Tools', weight: 0.83, aliases: ['Premiere Pro', 'Adobe Premiere', 'Premiere'] },
  { canonical: 'After Effects',      category: 'Tools', weight: 0.80, aliases: ['Adobe After Effects', 'AE'] },
  { canonical: 'Canva',              category: 'Tools', weight: 0.83, aliases: ['Canva Design'] },
  { canonical: 'Jira',               category: 'Tools', weight: 0.90, aliases: ['Jira Software', 'Atlassian Jira', 'JIRA'] },
  { canonical: 'Trello',             category: 'Tools', weight: 0.83, aliases: ['Trello Board'] },
  { canonical: 'Confluence',         category: 'Tools', weight: 0.83, aliases: ['Atlassian Confluence'] },
  { canonical: 'Notion',             category: 'Tools', weight: 0.83, aliases: ['Notion App'] },
  { canonical: 'Slack',              category: 'Tools', weight: 0.83, aliases: ['Slack App', 'Slack Workspace'] },
  { canonical: 'Agile',              category: 'Tools', weight: 0.90, aliases: ['Agile Methodology', 'Agile Development', 'Agile Framework'] },
  { canonical: 'Scrum',              category: 'Tools', weight: 0.87, aliases: ['Scrum Framework', 'Scrum Methodology'] },
  { canonical: 'Kanban',             category: 'Tools', weight: 0.83, aliases: ['Kanban Board', 'Kanban Methodology'] },
  { canonical: 'UI/UX Design',       category: 'Tools', weight: 0.88, aliases: ['UX Design', 'UI Design', 'User Interface Design', 'User Experience Design', 'UI/UX'] },
  { canonical: 'Wireframing',        category: 'Tools', weight: 0.83, aliases: ['Wireframes', 'Prototyping', 'Mockups'] },
  { canonical: 'npm',                category: 'Tools', weight: 0.83, aliases: ['Node Package Manager', 'NPM'] },
  { canonical: 'Yarn',               category: 'Tools', weight: 0.80, aliases: ['Yarn Package Manager'] },
  { canonical: 'Postman',            category: 'Tools', weight: 0.85, aliases: ['Postman API Tool'] },
]
