export default {
  "BSIT":           "Bachelor of Science in Information Technology",
  "BS IT":          "Bachelor of Science in Information Technology",
  "B.S.I.T.":       "Bachelor of Science in Information Technology",
  "BSCS":           "Bachelor of Science in Computer Science",
  "BS CS":          "Bachelor of Science in Computer Science",
  "BS ComSci":      "Bachelor of Science in Computer Science",
  "BS CompSci":     "Bachelor of Science in Computer Science",
  "BSCE":           "Bachelor of Science in Civil Engineering",
  "BS CE":          "Bachelor of Science in Civil Engineering",
  "BSEE":           "Bachelor of Science in Electrical Engineering",
  "BS EE":          "Bachelor of Science in Electrical Engineering",
  "BSME":           "Bachelor of Science in Mechanical Engineering",
  "BS ME":          "Bachelor of Science in Mechanical Engineering",
  "BSIE":           "Bachelor of Science in Industrial Engineering",
  "BSCOE":          "Bachelor of Science in Computer Engineering",
  "BS CpE":         "Bachelor of Science in Computer Engineering",
  "BSN":            "Bachelor of Science in Nursing",
  "BS Nursing":     "Bachelor of Science in Nursing",
  "BSBA":           "Bachelor of Science in Business Administration",
  "BS BA":          "Bachelor of Science in Business Administration",
  "BSA":            "Bachelor of Science in Accountancy",
  "BS Accountancy": "Bachelor of Science in Accountancy",
  "BS Accounting":  "Bachelor of Science in Accounting",
  "BSED":           "Bachelor of Science in Education",
  "BS Education":   "Bachelor of Science in Education",
  "BEED":           "Bachelor of Elementary Education",
  "BSPSYCH":        "Bachelor of Science in Psychology",
  "BS Psychology":  "Bachelor of Science in Psychology",
  "BSTM":           "Bachelor of Science in Tourism Management",
  "BS Tourism":     "Bachelor of Science in Tourism Management",
  "BSHM":           "Bachelor of Science in Hospitality Management",
  "BSHRM":          "Bachelor of Science in Hotel and Restaurant Management",
  "BSEM":           "Bachelor of Science in Engineering Management",
  "BS Electronics": "Bachelor of Science in Electronics Engineering",
  "BSECE":          "Bachelor of Science in Electronics and Communications Engineering",
  "BSPHY":          "Bachelor of Science in Physical Therapy",
  "BSMT":           "Bachelor of Science in Medical Technology",
  "BSPT":           "Bachelor of Science in Physical Therapy",
  "AB":             "Bachelor of Arts",
  "AB Comm":        "Bachelor of Arts in Communication",
  "AB Pol Sci":     "Bachelor of Arts in Political Science",
  "AB English":     "Bachelor of Arts in English",
  "AB Journalism":  "Bachelor of Arts in Journalism",
  "AB Philosophy":  "Bachelor of Arts in Philosophy",
  "AB Economics":   "Bachelor of Arts in Economics",
  "BS":             "Bachelor of Science",
  "BA":             "Bachelor of Arts",
  "B.S.":           "Bachelor of Science",
  "B.A.":           "Bachelor of Arts",
  "BEng":           "Bachelor of Engineering",
  "BTech":          "Bachelor of Technology",
  "MS":             "Master of Science",
  "MS CS":          "Master of Science in Computer Science",
  "MSCS":           "Master of Science in Computer Science",
  "MS IT":          "Master of Science in Information Technology",
  "MSIT":           "Master of Science in Information Technology",
  "MS EE":          "Master of Science in Electrical Engineering",
  "MS ME":          "Master of Science in Mechanical Engineering",
  "MS CE":          "Master of Science in Civil Engineering",
  "M.S.":           "Master of Science",
  "MA":             "Master of Arts",
  "M.A.":           "Master of Arts",
  "MBA":            "Master of Business Administration",
  "MPA":            "Master of Public Administration",
  "MPH":            "Master of Public Health",
  "MEd":            "Master of Education",
  "M.Ed.":          "Master of Education",
  "MIS":            "Master of Information Systems",
  "MEng":           "Master of Engineering",
  "MTech":          "Master of Technology",
  "PhD":            "Doctor of Philosophy",
  "Ph.D":           "Doctor of Philosophy",
  "Ph.D.":          "Doctor of Philosophy",
  "DBA":            "Doctor of Business Administration",
  "MD":             "Doctor of Medicine",
  "JD":             "Juris Doctor",
  "LLB":            "Bachelor of Laws",
  "LLM":            "Master of Laws",
  "EdD":            "Doctor of Education",
  "Associate":      "Associate Degree",
  "AAS":            "Associate of Applied Science",
  "AS":             "Associate of Science",
  "AA":             "Associate of Arts",
  "Diploma":        "Diploma",
  "Certificate":    "Certificate",
  "TESDA NC II":    "TESDA National Certificate II",
  "NC II":          "National Certificate II",
  "NC I":           "National Certificate I",
  "NC III":         "National Certificate III"
}
